# Generated by Django 3.2.4 on 2021-06-19 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Phase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_members', models.IntegerField()),
                ('member1', models.CharField(max_length=20)),
                ('member2', models.CharField(max_length=20, null=True)),
                ('member3', models.CharField(max_length=20, null=True)),
                ('member4', models.CharField(max_length=20, null=True)),
                ('member5', models.CharField(max_length=20, null=True)),
                ('phase', models.CharField(choices=[('1', 'Identify'), ('2', 'Investigate'), ('3', 'Ideate'), ('4', 'Implement'), ('5', 'Inform')], default='1', max_length=1)),
                ('mentor', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.mentor')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(default='')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.phase')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.FileField(upload_to='uploads/')),
                ('phase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.phase')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.team')),
            ],
        ),
    ]
