# Generated by Django 3.2.4 on 2021-06-19 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20210619_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='mentor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.mentor'),
        ),
    ]
