# Generated by Django 3.2.4 on 2021-06-20 01:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20210620_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='phase1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='phase2_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='phase3_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='phase4_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='phase5_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='team',
            name='total_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['time'],
            },
        ),
    ]
